logging:
  level:
    root: info
  pattern:
    console:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_management_db?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: smuser
    password: sm12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

root:
    url: /api/v1/school-management

